version: '3.4'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
  postgres:
    restart: always
    image: ankane/pgvector:v0.4.1
    hostname: magick_db
    environment:
      POSTGRES_DB: magick
      POSTGRES_USER: magick
      POSTGRES_PASSWORD: magick_default_pw
    ports:
      - '5432:5432'
  s3:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minioaccesskey
      MINIO_SECRET_KEY: miniosecretkey
    ports:
      - '9000:9000'
    volumes:
      - s3-data:/data
  server:
    image: magickml/server
    restart: always
    ports:
      - '3030:3030'
    environment:
      REDIS_HOST: redis
      DATABASE_URL: postgresql://magick:magick_default_pw@postgres:5432/magick
      CLIENT_PLUGINS: github,rest,discord,twitter,loop,task,googleai,openai,search,bluesky,avatar,elevenlabs,database,anthropic,intent
      SERVER_PLUGINS: github,rest,discord,twitter,loop,task,googleai,openai,search,bluesky,elevenlabs,database,anthropic,intent
      NODE_OPTIONS: '--max-old-space-size=8192'
      PAGINATE_DEFAULT: 100
      PAGINATE_MAX: 1000
      JWT_SECRET: secret
      DUMMY_TOKEN: eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..SUWUnYMxRTxIgGD1.lCzhMnTVeWOBFBzDs4_ft6UCZIVhfk9VSw18-SNzSJjXB4yqwi7z3XJEO9FwbSybFkAjSoFHwYnizYhDsrouDn1xLS7Dqzwnn4I-V1-L0mXcmKXRAS8D1PQzR88CDsk-LIqkcZkkxQ8aoGmyVcKwAmlnAdYpPUEbJ7E3DEBCvA4UbY1iqdYmCWdD7NWeR_IDsWFMKP3jEqp3HPMJbbTitCb1_W-G0gnZ6cokK_JH9tpgbjAoWe0KRQB2Dr3B22-1qa9cPV8W13she2q_RR6SeTAM9iqwzufvuIu2b3Lu0fypQpcV4JyrwCawkZcjsdGQqateftfAQNYzUeSXVzZdWSZJOwHtDHpIMKh_SugqS3ASNrN2gqUEwvY2SOe60h__2ljLsSc.9qWEv3VNEKFpc6zmJv4n0A
      VITE_APP_FILE_SERVER_URL: http://localhost:65530
      VITE_APP_SPEECH_SERVER_URL: http://localhost:65532
      VITE_APP_TRUSTED_PARENT_URL: http://localhost:3000
      VITE_APP_POSTHOG_ENABLED: 'false'
      VITE_APP_POSTHOG_API_KEY: key
      POSTHOG_API_KEY: key
      VITE_APP_PRODUCTION: 'true'
      PRODUCTION: 'true'
      VITE_APP_STANDALONE: 'false'
      STANDALONE: 'false'
      REDISCLOUD_HOST: redis
      REDISCLOUD_URL: redis://redis:6379
      DEFAULT_OPENAI_KEY: keytouseforprod
      DEFAULT_GOOGLEAI_API_KEY: keytouseforprod
      OPENMETER_ENABLED: 'false'
      OPENMETER_TOKEN: token
      OPENMETER_ENDPOINT: localhost:8888
      UNSTRUCTURED_ENDPOINT: https://api.unstructured.io/general/v0/general
      AWS_ACCESS_KEY: key
      AWS_SECRET_KEY: secret
      AWS_REGION: region
      AWS_BUCKET_NAME: bucket_name
      AWS_BUCKET_ENDPOINT: endpoint
      CLOUD_AGENT_KEY: key
      DOCKER_BUILD: 'true'
  cloud-agent-manager:
    image: magickml/cloud-agent-manager
    restart: always
    ports:
      - '3031:3031'
    environment:
      REDIS_HOST: redis
      DATABASE_URL: postgresql://magick:magick_default_pw@postgres:5432/magick
      CLIENT_PLUGINS: github,rest,discord,twitter,loop,task,googleai,openai,search,bluesky,avatar,elevenlabs,database,anthropic,intent
      SERVER_PLUGINS: github,rest,discord,twitter,loop,task,googleai,openai,search,bluesky,elevenlabs,database,anthropic,intent
      NODE_OPTIONS: '--max-old-space-size=8192'
      PAGINATE_DEFAULT: 100
      PAGINATE_MAX: 1000
      JWT_SECRET: secret
      DUMMY_TOKEN: eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..SUWUnYMxRTxIgGD1.lCzhMnTVeWOBFBzDs4_ft6UCZIVhfk9VSw18-SNzSJjXB4yqwi7z3XJEO9FwbSybFkAjSoFHwYnizYhDsrouDn1xLS7Dqzwnn4I-V1-L0mXcmKXRAS8D1PQzR88CDsk-LIqkcZkkxQ8aoGmyVcKwAmlnAdYpPUEbJ7E3DEBCvA4UbY1iqdYmCWdD7NWeR_IDsWFMKP3jEqp3HPMJbbTitCb1_W-G0gnZ6cokK_JH9tpgbjAoWe0KRQB2Dr3B22-1qa9cPV8W13she2q_RR6SeTAM9iqwzufvuIu2b3Lu0fypQpcV4JyrwCawkZcjsdGQqateftfAQNYzUeSXVzZdWSZJOwHtDHpIMKh_SugqS3ASNrN2gqUEwvY2SOe60h__2ljLsSc.9qWEv3VNEKFpc6zmJv4n0A
      VITE_APP_FILE_SERVER_URL: http://localhost:65530
      VITE_APP_SPEECH_SERVER_URL: http://localhost:65532
      VITE_APP_TRUSTED_PARENT_URL: http://localhost:3000
      VITE_APP_POSTHOG_ENABLED: 'false'
      VITE_APP_POSTHOG_API_KEY: key
      POSTHOG_API_KEY: key
      VITE_APP_PRODUCTION: 'true'
      PRODUCTION: 'true'
      VITE_APP_STANDALONE: 'false'
      STANDALONE: 'false'
      REDISCLOUD_HOST: redis
      REDISCLOUD_URL: redis://redis:6379
      DEFAULT_OPENAI_KEY: keytouseforprod
      DEFAULT_GOOGLEAI_API_KEY: keytouseforprod
      OPENMETER_ENABLED: 'false'
      OPENMETER_TOKEN: token
      OPENMETER_ENDPOINT: localhost:8888
      UNSTRUCTURED_ENDPOINT: https://api.unstructured.io/general/v0/general
      AWS_ACCESS_KEY: key
      AWS_SECRET_KEY: secret
      AWS_REGION: region
      AWS_BUCKET_NAME: bucket_name
      AWS_BUCKET_ENDPOINT: endpoint
      CLOUD_AGENT_KEY: key
      DOCKER_BUILD: 'true'
  cloud-agent-worker:
    image: magickml/cloud-agent-worker
    restart: always
    ports:
      - '3032:3032'
    environment:
      REDIS_HOST: redis
      DATABASE_URL: postgresql://magick:magick_default_pw@postgres:5432/magick
      CLIENT_PLUGINS: github,rest,discord,twitter,loop,task,googleai,openai,search,bluesky,avatar,elevenlabs,database,anthropic,intent
      SERVER_PLUGINS: github,rest,discord,twitter,loop,task,googleai,openai,search,bluesky,elevenlabs,database,anthropic,intent
      NODE_OPTIONS: '--max-old-space-size=8192'
      PAGINATE_DEFAULT: 100
      PAGINATE_MAX: 1000
      JWT_SECRET: secret
      DUMMY_TOKEN: eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..SUWUnYMxRTxIgGD1.lCzhMnTVeWOBFBzDs4_ft6UCZIVhfk9VSw18-SNzSJjXB4yqwi7z3XJEO9FwbSybFkAjSoFHwYnizYhDsrouDn1xLS7Dqzwnn4I-V1-L0mXcmKXRAS8D1PQzR88CDsk-LIqkcZkkxQ8aoGmyVcKwAmlnAdYpPUEbJ7E3DEBCvA4UbY1iqdYmCWdD7NWeR_IDsWFMKP3jEqp3HPMJbbTitCb1_W-G0gnZ6cokK_JH9tpgbjAoWe0KRQB2Dr3B22-1qa9cPV8W13she2q_RR6SeTAM9iqwzufvuIu2b3Lu0fypQpcV4JyrwCawkZcjsdGQqateftfAQNYzUeSXVzZdWSZJOwHtDHpIMKh_SugqS3ASNrN2gqUEwvY2SOe60h__2ljLsSc.9qWEv3VNEKFpc6zmJv4n0A
      VITE_APP_FILE_SERVER_URL: http://localhost:65530
      VITE_APP_SPEECH_SERVER_URL: http://localhost:65532
      VITE_APP_TRUSTED_PARENT_URL: http://localhost:3000
      VITE_APP_POSTHOG_ENABLED: 'false'
      VITE_APP_POSTHOG_API_KEY: key
      POSTHOG_API_KEY: key
      VITE_APP_PRODUCTION: 'true'
      PRODUCTION: 'true'
      VITE_APP_STANDALONE: 'false'
      STANDALONE: 'false'
      REDISCLOUD_HOST: redis
      REDISCLOUD_URL: redis://redis:6379
      DEFAULT_OPENAI_KEY: keytouseforprod
      DEFAULT_GOOGLEAI_API_KEY: keytouseforprod
      OPENMETER_ENABLED: 'false'
      OPENMETER_TOKEN: token
      OPENMETER_ENDPOINT: localhost:8888
      UNSTRUCTURED_ENDPOINT: https://api.unstructured.io/general/v0/general
      AWS_ACCESS_KEY: key
      AWS_SECRET_KEY: secret
      AWS_REGION: region
      AWS_BUCKET_NAME: bucket_name
      AWS_BUCKET_ENDPOINT: endpoint
      CLOUD_AGENT_KEY: key
      DOCKER_BUILD: 'true'
  client:
    image: magickml/client
    restart: always
    ports:
      - '4200:80'
    environment:
      REDIS_HOST: redis
      DATABASE_URL: postgresql://magick:magick_default_pw@postgres:5432/magick
      CLIENT_PLUGINS: github,rest,discord,twitter,loop,task,googleai,openai,search,bluesky,avatar,elevenlabs,database,anthropic,intent
      SERVER_PLUGINS: github,rest,discord,twitter,loop,task,googleai,openai,search,bluesky,elevenlabs,database,anthropic,intent
      NODE_OPTIONS: '--max-old-space-size=8192'
      PAGINATE_DEFAULT: 100
      PAGINATE_MAX: 1000
      JWT_SECRET: secret
      DUMMY_TOKEN: eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..SUWUnYMxRTxIgGD1.lCzhMnTVeWOBFBzDs4_ft6UCZIVhfk9VSw18-SNzSJjXB4yqwi7z3XJEO9FwbSybFkAjSoFHwYnizYhDsrouDn1xLS7Dqzwnn4I-V1-L0mXcmKXRAS8D1PQzR88CDsk-LIqkcZkkxQ8aoGmyVcKwAmlnAdYpPUEbJ7E3DEBCvA4UbY1iqdYmCWdD7NWeR_IDsWFMKP3jEqp3HPMJbbTitCb1_W-G0gnZ6cokK_JH9tpgbjAoWe0KRQB2Dr3B22-1qa9cPV8W13she2q_RR6SeTAM9iqwzufvuIu2b3Lu0fypQpcV4JyrwCawkZcjsdGQqateftfAQNYzUeSXVzZdWSZJOwHtDHpIMKh_SugqS3ASNrN2gqUEwvY2SOe60h__2ljLsSc.9qWEv3VNEKFpc6zmJv4n0A
      VITE_APP_FILE_SERVER_URL: http://localhost:65530
      VITE_APP_SPEECH_SERVER_URL: http://localhost:65532
      VITE_APP_TRUSTED_PARENT_URL: http://localhost:3000
      VITE_APP_POSTHOG_ENABLED: 'false'
      VITE_APP_POSTHOG_API_KEY: key
      POSTHOG_API_KEY: key
      VITE_APP_PRODUCTION: 'true'
      PRODUCTION: 'true'
      VITE_APP_STANDALONE: 'false'
      STANDALONE: 'false'
      REDISCLOUD_HOST: redis
      REDISCLOUD_URL: redis://redis:6379
      DEFAULT_OPENAI_KEY: keytouseforprod
      DEFAULT_GOOGLEAI_API_KEY: keytouseforprod
      OPENMETER_ENABLED: 'false'
      OPENMETER_TOKEN: token
      OPENMETER_ENDPOINT: localhost:8888
      UNSTRUCTURED_ENDPOINT: https://api.unstructured.io/general/v0/general
      AWS_ACCESS_KEY: key
      AWS_SECRET_KEY: secret
      AWS_REGION: region
      AWS_BUCKET_NAME: bucket_name
      AWS_BUCKET_ENDPOINT: endpoint
      CLOUD_AGENT_KEY: key
      DOCKER_BUILD: 'true'

volumes:
  cache:
    driver: local
  s3-data:
    driver: local

networks:
  default:
    name: magick-network
