steps:
  - name: 'node:18'
    entrypoint: npm
    args:
      - install
  - name: 'node:18'
    entrypoint: npm
    args:
      - run
      - build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/server:${_SHORT_SHA}'
      - '-f'
      - 'apps/server/Dockerfile'
      - '--build-arg'
      - 'DATABASE_URL=${_DATABASE_URL}'
      - '--build-arg'
      - 'NODE_OPTIONS=${_NODE_OPTIONS}'
      - '--build-arg'
      - 'JWT_SECRET=${_JWT_SECRET}'
      - '--build-arg'
      - 'DUMMY_TOKEN=${_DUMMY_TOKEN}'
      - '--build-arg'
      - 'VITE_APP_FILE_SERVER_URL=${_VITE_APP_FILE_SERVER_URL}'
      - '--build-arg'
      - 'VITE_APP_SPEECH_SERVER_URL=${_VITE_APP_SPEECH_SERVER_URL}'
      - '--build-arg'
      - 'VITE_APP_TRUSTED_PARENT_URL=${_VITE_APP_TRUSTED_PARENT_URL}'
      - '--build-arg'
      - 'VITE_APP_POSTHOG_ENABLED=${_VITE_APP_POSTHOG_ENABLED}'
      - '--build-arg'
      - 'VITE_APP_POSTHOG_API_KEY=${_VITE_APP_POSTHOG_API_KEY}'
      - '--build-arg'
      - 'POSTHOG_API_KEY=${_POSTHOG_API_KEY}'
      - '--build-arg'
      - 'VITE_APP_PRODUCTION=${_VITE_APP_PRODUCTION}'
      - '--build-arg'
      - 'PRODUCTION=${_PRODUCTION}'
      - '--build-arg'
      - 'VITE_APP_STANDALONE=${_VITE_APP_STANDALONE}'
      - '--build-arg'
      - 'STANDALONE=${_STANDALONE}'
      - '--build-arg'
      - 'REDISCLOUD_HOST=${_REDISCLOUD_HOST}'
      - '--build-arg'
      - 'REDISCLOUD_URL=${_REDISCLOUD_URL}'
      - '--build-arg'
      - 'DEFAULT_OPENAI_KEY=${_DEFAULT_OPENAI_KEY}'
      - '--build-arg'
      - 'DEFAULT_GOOGLEAI_API_KEY=${_DEFAULT_GOOGLEAI_API_KEY}'
      - '--build-arg'
      - 'OPENMETER_ENABLED=${_OPENMETER_ENABLED}'
      - '--build-arg'
      - 'OPENMETER_TOKEN=${_OPENMETER_TOKEN}'
      - '--build-arg'
      - 'OPENMETER_ENDPOINT=${_OPENMETER_ENDPOINT}'
      - '--build-arg'
      - 'UNSTRUCTURED_ENDPOINT=${_UNSTRUCTURED_ENDPOINT}'
      - '--build-arg'
      - 'AWS_ACCESS_KEY=${_AWS_ACCESS_KEY}'
      - '--build-arg'
      - 'AWS_SECRET_KEY=${_AWS_SECRET_KEY}'
      - '--build-arg'
      - 'AWS_REGION=${_AWS_REGION}'
      - '--build-arg'
      - 'AWS_BUCKET_NAME=${_AWS_BUCKET_NAME}'
      - '--build-arg'
      - 'AWS_BUCKET_ENDPOINT=${_AWS_BUCKET_ENDPOINT}'
      - '--build-arg'
      - 'CLOUD_AGENT_KEY=${_CLOUD_AGENT_KEY}'
      - '--build-arg'
      - 'CLIENT_PLUGINS=${_CLIENT_PLUGINS}'
      - '--build-arg'
      - 'SERVER_PLUGINS=${_SERVER_PLUGINS}'
      - '.'
    env:
      - 'CLIENT_PLUGINS=${_CLIENT_PLUGINS}'
      - 'SERVER_PLUGINS=${_SERVER_PLUGINS}'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT_ID}/server:${_SHORT_SHA}']

images:
  - 'gcr.io/${_PROJECT_ID}/server:${_SHORT_SHA}'

substitutions:
  _PROJECT_ID: 'magick-387817'
  _SHORT_SHA: 'latest'
  _DATABASE_URL: 'postgresql://magick:magick_default_pw@localhost:5432/magick'
  _NODE_OPTIONS: '--max-old-space-size=8192'
  _JWT_SECRET: 'secret'
  _DUMMY_TOKEN: 'dummy_token'
  _VITE_APP_FILE_SERVER_URL: 'http://localhost:65530'
  _VITE_APP_SPEECH_SERVER_URL: 'http://localhost:65532'
  _VITE_APP_TRUSTED_PARENT_URL: 'http://localhost:3000'
  _VITE_APP_POSTHOG_ENABLED: 'false'
  _VITE_APP_POSTHOG_API_KEY: 'key'
  _POSTHOG_API_KEY: 'phc_TxdF63jquubjgifJOYWFQpeXUN1klGcylArpkCm6kfQ'
  _VITE_APP_PRODUCTION: 'false'
  _PRODUCTION: 'false'
  _VITE_APP_STANDALONE: 'true'
  _STANDALONE: 'true'
  _REDISCLOUD_HOST: 'localhost'
  _REDISCLOUD_URL: 'redis://localhost:6379'
  _DEFAULT_OPENAI_KEY: 'keytouseforprod'
  _DEFAULT_GOOGLEAI_API_KEY: 'keytouseforprod'
  _OPENMETER_ENABLED: 'false'
  _OPENMETER_TOKEN: 'token'
  _OPENMETER_ENDPOINT: 'localhost:8888'
  _UNSTRUCTURED_ENDPOINT: 'https://api.unstructured.io/general/v0/general'
  _AWS_ACCESS_KEY: 'key'
  _AWS_SECRET_KEY: 'secret'
  _AWS_REGION: 'region'
  _AWS_BUCKET_NAME: 'bucket_name'
  _AWS_BUCKET_ENDPOINT: 'endpoint'
  _CLOUD_AGENT_KEY: 'key'
  _CLIENT_PLUGINS: 'github,rest,discord,twitter,loop,task,googleai,openai,search,bluesky,avatar,elevenlabs,database,anthropic,intent'
  _SERVER_PLUGINS: 'github,rest,discord,twitter,loop,task,googleai,openai,search,bluesky,elevenlabs,database,anthropic,intent'

timeout: '1200s'
