serviceAccount: projects/magick-387817/serviceAccounts/magick-dev-service@magick-387817.iam.gserviceaccount.com
steps:
  - name: 'node:18'
    entrypoint: npm
    args:
      - install

  - name: 'node:18'
    entrypoint: npm
    args:
      - run
      - build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--build-arg'
      - 'CLIENT_PLUGINS=${_CLIENT_PLUGINS}'
      - '--build-arg'
      - 'SERVER_PLUGINS=${_SERVER_PLUGINS}'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/server:${_SHORT_SHA}'
      - '-f'
      - './apps/client/Dockerfile'
      - '.'
    secretEnv: [
      'DATABASE_URL',
      'CLIENT_PLUGINS',
      'SERVER_PLUGINS',
      NODE_OPTIONS,
      JWT_SECRET,
      DUMMY_TOKEN,
      VITE_APP_FILE_SERVER_URL,
      VITE_APP_SPEECH_SERVER_URL,
      VITE_APP_TRUSTED_PARENT_URL,
      VITE_APP_POSTHOG_ENABLED,
      VITE_APP_POSTHOG_API_KEY,
      POSTHOG_API_KEY,
      VITE_APP_PRODUCTION,
      PRODUCTION,
      VITE_APP_STANDALONE,
      STANDALONE,
      REDISCLOUD_HOST,
      REDISCLOUD_URL,
      DEFAULT_OPENAI_KEY,
      DEFAULT_GOOGLEAI_API_KEY,
      OPENMETER_ENABLED,
      OPENMETER_TOKEN,
      OPENMETER_ENDPOINT,
      UNSTRUCTURED_ENDPOINT,
      AWS_ACCESS_KEY,
      AWS_SECRET_KEY,
      AWS_REGION,
      AWS_BUCKET_NAME,
      AWS_BUCKET_ENDPOINT,
      CLOUD_AGENT_KEY
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT_ID}/server:${_SHORT_SHA}']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL-MAGICK-DEV/versions/latest
      env: 'DATABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/CLIENT_PLUGINS-MAGICK-DEV/versions/latest
      env: 'CLIENT_PLUGINS'
    - versionName: projects/$PROJECT_ID/secrets/SERVER_PLUGINS-MAGICK-DEV/versions/latest
      env: 'SERVER_PLUGINS'
    - versionName: projects/$PROJECT_ID/secrets/NODE_OPTIONS-MAGICK-DEV/versions/latest
      env: 'NODE_OPTIONS'
    - versionName: projects/$PROJECT_ID/secrets/JWT_SECRET-MAGICK-DEV/versions/latest
      env: 'JWT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/DUMMY_TOKEN-MAGICK-DEV/versions/latest
      env: 'DUMMY_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/VITE_APP_FILE_SERVER_URL-MAGICK-DEV/versions/latest
      env: 'VITE_APP_FILE_SERVER_URL'
    - versionName: projects/$PROJECT_ID/secrets/VITE_APP_SPEECH_SERVER_URL-MAGICK-DEV/versions/latest
      env: 'VITE_APP_SPEECH_SERVER_URL'
    - versionName: projects/$PROJECT_ID/secrets/VITE_APP_TRUSTED_PARENT_URL-MAGICK-DEV/versions/latest
      env: 'VITE_APP_TRUSTED_PARENT_URL'
    - versionName: projects/$PROJECT_ID/secrets/VITE_APP_POSTHOG_ENABLED-MAGICK-DEV/versions/latest
      env: 'VITE_APP_POSTHOG_ENABLED'
    - versionName: projects/$PROJECT_ID/secrets/VITE_APP_POSTHOG_API_KEY-MAGICK-DEV/versions/latest
      env: 'VITE_APP_POSTHOG_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/POSTHOG_API_KEY-MAGICK-DEV/versions/latest
      env: 'POSTHOG_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/VITE_APP_PRODUCTION-MAGICK-DEV/versions/latest
      env: 'VITE_APP_PRODUCTION'
    - versionName: projects/$PROJECT_ID/secrets/PRODUCTION-MAGICK-DEV/versions/latest
      env: 'PRODUCTION'
    - versionName: projects/$PROJECT_ID/secrets/VITE_APP_STANDALONE-MAGICK-DEV/versions/latest
      env: 'VITE_APP_STANDALONE'
    - versionName: projects/$PROJECT_ID/secrets/STANDALONE-MAGICK-DEV/versions/latest
      env: 'STANDALONE'
    - versionName: projects/$PROJECT_ID/secrets/REDISCLOUD_HOST-MAGICK-DEV/versions/latest
      env: 'REDISCLOUD_HOST'
    - versionName: projects/$PROJECT_ID/secrets/REDISCLOUD_URL-MAGICK-DEV/versions/latest
      env: 'REDISCLOUD_URL'
    - versionName: projects/$PROJECT_ID/secrets/DEFAULT_OPENAI_KEY-MAGICK-DEV/versions/latest
      env: 'DEFAULT_OPENAI_KEY'
    - versionName: projects/$PROJECT_ID/secrets/DEFAULT_GOOGLEAI_API_KEY-MAGICK-DEV/versions/latest
      env: 'DEFAULT_GOOGLEAI_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/OPENMETER_ENABLED-MAGICK-DEV/versions/latest
      env: 'OPENMETER_ENABLED'
    - versionName: projects/$PROJECT_ID/secrets/OPENMETER_TOKEN-MAGICK-DEV/versions/latest
      env: 'OPENMETER_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/OPENMETER_ENDPOINT-MAGICK-DEV/versions/latest
      env: 'OPENMETER_ENDPOINT'
    - versionName: projects/$PROJECT_ID/secrets/UNSTRUCTURED_ENDPOINT-MAGICK-DEV/versions/latest
      env: 'UNSTRUCTURED_ENDPOINT'
    - versionName: projects/$PROJECT_ID/secrets/AWS_ACCESS_KEY-MAGICK-DEV/versions/latest
      env: 'AWS_ACCESS_KEY'
    - versionName: projects/$PROJECT_ID/secrets/AWS_SECRET_KEY-MAGICK-DEV/versions/latest
      env: 'AWS_SECRET_KEY'
    - versionName: projects/$PROJECT_ID/secrets/AWS_REGION-MAGICK-DEV/versions/latest
      env: 'AWS_REGION'
    - versionName: projects/$PROJECT_ID/secrets/AWS_BUCKET_NAME-MAGICK-DEV/versions/latest
      env: 'AWS_BUCKET_NAME'
    - versionName: projects/$PROJECT_ID/secrets/AWS_BUCKET_ENDPOINT-MAGICK-DEV/versions/latest
      env: 'AWS_BUCKET_ENDPOINT'
    - versionName: projects/$PROJECT_ID/secrets/CLOUD_AGENT_KEY-MAGICK-DEV/versions/latest
      env: 'CLOUD_AGENT_KEY'


images:
  - 'gcr.io/${_PROJECT_ID}/server:${_SHORT_SHA}'
substitutions:
  _PROJECT_ID: 'magick-387817'
  _SHORT_SHA: 'latest'
  _CLIENT_PLUGINS: 'github,rest,discord,twitter,loop,task,googleai,openai,search,bluesky,avatar,elevenlabs,database,anthropic,intent'
  _SERVER_PLUGINS: 'github,rest,discord,twitter,loop,task,googleai,openai,search,bluesky,elevenlabs,database,anthropic,intent'

timeout: '1200s'
