apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: server-service
  namespace: 'default'
spec:
  template:
    spec:
      containers:
      - image: gcr.io/$PROJECT_ID/server:$SHORT_SHA
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
        envFrom:
        - secretRef:
            name: server-secrets
