steps:
  - name: 'node:18'
    entrypoint: npm
    args:
      - install
  - name: 'node:18'
    entrypoint: npm
    args:
      - run
      - build-client

  # Client
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/client:latest'
      - '-f'
      - './apps/client/Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/client:latest'

images:
  - 'gcr.io/$PROJECT_ID/client:latest'


substitutions:
  _PROJECT_ID: 'magick-387817'
  _SHORT_SHA: 'latest'
  _CLIENT_PLUGINS: github,rest,discord,twitter,loop,task,googleai,openai,search,bluesky,avatar,elevenlabs,database,anthropic,intent
  _SERVER_PLUGINS: github,rest,discord,twitter,loop,task,googleai,openai,search,bluesky,elevenlabs,database,anthropic,intent
